#!/bin/sh
# Build fleet-ui.jar (a dex for app_process) and regenerate src/android-ui-jar.ts,
# which embeds it so a compiled fleet can install it on a phone.
# Needs a JDK and the Android SDK (platforms/android-36, build-tools with d8).
set -eu
here=$(cd "$(dirname "$0")" && pwd)
sdk=${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Library/Android/sdk}}
jar="$sdk/platforms/android-36/android.jar"
d8=$(ls "$sdk"/build-tools/*/d8 | sort -V | tail -1)
out=$(mktemp -d)
trap 'rm -rf "$out"' EXIT
javac --release 11 -classpath "$jar" -d "$out/classes" "$here/src/fleet/UiServer.java"
"$d8" --min-api 26 --lib "$jar" --output "$out/fleet-ui.jar" $(find "$out/classes" -name '*.class')
cp "$out/fleet-ui.jar" "$here/fleet-ui.jar"
md5=$(md5 -q "$here/fleet-ui.jar" 2>/dev/null || md5sum "$here/fleet-ui.jar" | cut -d' ' -f1)
{
  echo "// Generated by android/uiserver/build.sh from android/uiserver/src. Do not edit."
  echo "export const UI_JAR_MD5 = \"$md5\";"
  printf 'export const UI_JAR_B64 = "%s";\n' "$(base64 < "$here/fleet-ui.jar" | tr -d '\n')"
} > "$here/../../src/android-ui-jar.ts"
echo "fleet-ui.jar $(wc -c < "$here/fleet-ui.jar") bytes, md5 $md5"
